openapi: 3.0.0
info:
  title: API
  version: '0.1.0'
  description: Yepl Insides Api
paths:
  /business/name/{name}:
    get:
      summary: Get business by name
      parameters:
        - name: name
          in: path
          required: true
          description: Business name
          schema:
            type: string
        - name: state
          in: query
          description: State (optional)
          schema:
            type: string
        - name: postal_code
          in: query
          description: Postal code (optional)
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: { oid: 6569e7e121a6cf9c8f45958b }
                business_id: mpf3x-BjTdTEA3yCZrAYPw
                name: The UPS Store
                address: 87 Grasso Plaza Shopping Center
                city: Affton
                state: MO
                postal_code: 63123
                latitude: 38.551126
                longitude: -90.335695
                stars: 3
                review_count: 15
                is_open: 1
                attributes: { BusinessAcceptsCreditCards: True }
                categories: Shipping Centers, Local Services, Notaries, Mailbox Centers, Printing Services
                hours: { Monday: 0:0-0:0, Tuesday: 8:0-18:30, Wednesday: 8:0-18:30, Thursday: 8:0-18:30, Friday: 8:0-18:30, Saturday: 8:0-14:0 }
  /business/{business_id}:
    get:
      summary: Get business by ID
      parameters:
        - name: business_id
          in: path
          required: true
          description: Business ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: { oid: 6569e7e121a6cf9c8f45958b }
                business_id: mpf3x-BjTdTEA3yCZrAYPw
                name: The UPS Store
                address: 87 Grasso Plaza Shopping Center
                city: Affton
                state: MO
                postal_code: 63123
                latitude: 38.551126
                longitude: -90.335695
                stars: 3
                review_count: 15
                is_open: 1
                attributes: { BusinessAcceptsCreditCards: True }
                categories: Shipping Centers, Local Services, Notaries, Mailbox Centers, Printing Services
                hours: { Monday: 0:0-0:0, Tuesday: 8:0-18:30, Wednesday: 8:0-18:30, Thursday: 8:0-18:30, Friday: 8:0-18:30, Saturday: 8:0-14:0 }
  /reviews/{business_id}:
    get:
      summary: Get reviews for a business
      parameters:
        - name: business_id
          in: path
          required: true
          description: Business ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: { oid: 6569e7e121a6cf9c8f45958b }
                review_id: -WXMS4p3D9NQsAPw4YPEyw
                user_id: Jks_uMtTZHqP-84wSZ3COg
                business_id: mpf3x-BjTdTEA3yCZrAYPw
                stars: 5
                useful: 0
                funny: 0
                cool: 0
                text: I have a po box there and ea. visit I am greeted with "hello". Asked the owner to wrap n send a family heirloom pic in a frame. They went the extra mile to assure safe travel. Received without damage. I was relieved n happy I had them handle.
                date: 2014-09-15 14:37:42
  /reviews/trends/{business_id}:
    get:
      summary: Get trends for reviews of a business
      parameters:
        - name: business_id
          in: path
          required: true
          description: Business ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                business_id: mpf3x-BjTdTEA3yCZrAYPw
                reviews_count: 34
                avg_stars: 2.4
  /reviews/checkstars/{business_id}:
    get:
      summary: Check stars for last 10 reviews of a business
      parameters:
        - name: business_id
          in: path
          required: true
          description: Business ID
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                business_id: mpf3x-BjTdTEA3yCZrAYPw
                reviews_count: 5
                avg_stars: 3.8